BSDT-49: Web list "news press"
Dimas0006/BabyAQAsTeam pull request #9
Opened 2023-07-04 09:31 UTC by Dimas0006

2023-07-04 09:45 UTC, tetianaromaniuk approved these changes

2023-07-05 13:53 UTC, AndriiMyronenko91 requested changes

2023-07-05 13:53 UTC, AndriiMyronenko91 commented on src/test/java/pages/MenuRegisterPage.java
> +    private static final String MENU_LIST_TYPE_ORGANIZATION = "//select[@id='mfc_lead_type-a2493124-5ff8-47bd-bf1a-9ff97c3b90a2']//option[@value='Community/Other']";
please change locators to more understandable if possible

2023-07-05 13:53 UTC, AndriiMyronenko91 commented on src/test/java/pages/MenuRegisterPage.java
> +    private static final String RADIO_BUTTON = "//input[@id='mfc__teamgrouptype_community_other2-a2493124-5ff8-47bd-bf1a-9ff97c3b90a2']";
same. you can use Xpath contains

2023-07-05 13:53 UTC, AndriiMyronenko91 commented on src/test/java/tests/TestingRegistration.java
> +    private static final String YOUR_PASSWORD = "12345678";
it is better to create a class TestUser where you can define your test user so other developers could use it

2023-07-05 15:01 UTC, AndriiMyronenko91 approved these changes

2023-07-05 15:01 UTC, merged